import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { execFileSync, spawnSync } from 'node:child_process';
import { readIsolationContext, writeIsolationContext } from '../../scripts/lib/isolation-context.mjs';
const cli = resolve('scripts/spec-superflow.mjs');
test('finish invoked inside isolation merges into the actual target and never force-removes files', t => {
  const root = fs.mkdtempSync(join(tmpdir(), 'ssf-finish-regression-'));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  const main = join(root, 'repo'), wt = join(root, 'wt');
  fs.mkdirSync(main);
  const env = { ...process.env, GIT_AUTHOR_NAME: 'Test', GIT_AUTHOR_EMAIL: 'test@example.test', GIT_COMMITTER_NAME: 'Test', GIT_COMMITTER_EMAIL: 'test@example.test' };
  const git = (cwd, ...args) => execFileSync('git', ['-C', cwd, ...args], { env, encoding: 'utf8', stdio: 'pipe' }).trim();
  git(main, 'init', '-b', 'main');
  fs.writeFileSync(join(main, '.gitignore'), 'changes/\n');
  git(main, 'add', '.'); git(main, 'commit', '-m', 'base');
  git(main, 'worktree', 'add', wt, '-b', 'demo');
  const change = join(wt, 'openspec', 'changes', 'demo');
  fs.mkdirSync(change, { recursive: true });
  fs.writeFileSync(join(change, '.spec-superflow.yaml'), 'state: closing\nworkflow: full\n');
  fs.mkdirSync(join(change, '.superpowers', 'sdd', 'reviews', 'snapshots'), { recursive: true });
  fs.writeFileSync(join(change, '.superpowers', 'sdd', 'reviews', 'snapshots', 'final.md'), 'Final evidence');
  const oldTarget = join(main, 'openspec', 'changes', 'demo');
  fs.mkdirSync(oldTarget, { recursive: true });
  fs.writeFileSync(join(oldTarget, 'original-note.md'), 'Original user note');
  fs.writeFileSync(join(oldTarget, '.spec-superflow.yaml'), 'state: executing\nworkflow: full\n');
  fs.writeFileSync(join(wt, 'feature.txt'), 'feature');
  git(wt, 'add', '.'); git(wt, 'commit', '-m', 'feature');
  const run = () => spawnSync(process.execPath, [cli, 'finish', change, '--test-cmd', 'node -e "process.exit(0)"'], { cwd: wt, env, encoding: 'utf8' });
  fs.writeFileSync(join(wt, 'keep.txt'), 'untracked');
  assert.notEqual(run().status, 0);
  assert.equal(fs.readFileSync(join(wt, 'keep.txt'), 'utf8'), 'untracked');
  fs.unlinkSync(join(wt, 'keep.txt'));
  const result = run();
  assert.equal(result.status, 0, result.stdout + result.stderr);
  assert.equal(fs.readFileSync(join(main, 'feature.txt'), 'utf8'), 'feature');
  assert.equal(fs.existsSync(wt), false);
  assert.equal(fs.readFileSync(join(main, 'openspec', 'changes', 'demo', '.superpowers', 'sdd', 'reviews', 'snapshots', 'final.md'), 'utf8'), 'Final evidence');
  assert.match(fs.readFileSync(join(main, 'openspec', 'changes', 'demo', '.spec-superflow.yaml'), 'utf8'), /state: closing/);
  const archived = readIsolationContext(oldTarget).change_archive;
  assert.equal(fs.readFileSync(join(archived.archive, 'previous-target', 'original-note.md'), 'utf8'), 'Original user note');
});

test('branch-only finish switches to its recorded target and retains the checkout', t => {
  const root = fs.mkdtempSync(join(tmpdir(), 'ssf-branch-finish-'));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  const env = { ...process.env, GIT_AUTHOR_NAME: 'Test', GIT_AUTHOR_EMAIL: 'test@example.test', GIT_COMMITTER_NAME: 'Test', GIT_COMMITTER_EMAIL: 'test@example.test' };
  const git = (...args) => execFileSync('git', ['-C', root, ...args], { env, encoding: 'utf8', stdio: 'pipe' }).trim();
  git('init', '-b', 'main');
  fs.writeFileSync(join(root, '.gitignore'), 'changes/\n');
  git('add', '.'); git('commit', '-m', 'base'); git('switch', '-c', 'demo');
  const dir = join(root, 'openspec', 'changes', 'demo');
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(join(dir, '.spec-superflow.yaml'), 'state: closing\n');
  fs.writeFileSync(join(root, 'feature.txt'), 'feature');
  git('add', '.'); git('commit', '-m', 'feature');
  writeIsolationContext(dir, { change_name: 'demo', target_root: root, target_branch: 'main', isolation_root: root, isolation_branch: 'demo', kind: 'branch', finish_status: 'pending' });
  const result = spawnSync(process.execPath, [cli, 'finish', dir, '--test-cmd', 'node -e "process.exit(0)"'], { cwd: root, env, encoding: 'utf8' });
  assert.equal(result.status, 0, result.stdout + result.stderr);
  assert.equal(git('branch', '--show-current'), 'main');
  assert.equal(fs.readFileSync(join(root, 'feature.txt'), 'utf8'), 'feature');
  assert.equal(fs.existsSync(dir), true);
});
